version: '3'

services:
  
  mongo:
    image: mongo:latest
    container_name: mongo
    command: mongod --smallfiles
    restart: always
    networks:
      bitdb-net:
        ipv4_address: 172.21.0.10
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./mongo:/data/db
    environment:
      - "MONGODB_USER=bitcore"
      - "MONGODB_PASS=bitcore"
      - "MONGODB_ENABLE_IPV6=no"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    networks:
      bitdb-net:
        ipv4_address: 172.21.0.11
    ports:
      - 8081:8081
    environment:
      - "ME_CONFIG_OPTIONS_EDITORTHEME=ambiance"
      - "ME_CONFIG_BASICAUTH_USERNAME=bitcore"
      - "ME_CONFIG_BASICAUTH_PASSWORD=bitcore"
 
  bitcored:
    image: dalijolijo/bitcored-bitdb
    container_name: bitcored-bitdb
    command: -rpcuser=root -rpcpassword=bitcore
    restart: always
    networks:
      bitdb-net:
        ipv4_address: 172.21.0.12
    ports:
      - 8555:8555
    expose:
      - 8556
    volumes:
      - ./bitcore:/data 
  
  bitdb-btx:
    build:
      context: ./docker
      dockerfile: ./Dockerfile.bitdb-btx
    image: bitd-btx
    container_name: bitdb-btx
    working_dir: "/bitdb"
    command: bash -c "sleep 60 && npm start"
    restart: always
    networks:
      bitdb-net:
        ipv4_address: 172.21.0.13
    ports:
      - 28555:28555
    expose:
      - 28556
    environment:
      - "MONGODB_URL='mongodb://172.21.0.10:27017'"
      - "RPC_HOST=172.21.0.12"
    depends_on:
      - mongo
      - bitcored
  
  # BitDB Explorer : http://localhost:3001/
  bitserve:
    build:
      context: ./docker
      dockerfile: ./Dockerfile.bitserve
    image: bitserve
    container_name: bitserve
    working_dir: "/bitserve"
    command: bash -c "sleep 10 && npm start"
    restart: always
    networks:
      bitdb-net:
        ipv4_address: 172.21.0.14
    ports:
      - 3001:3001
    depends_on:
      - mongo
  
  # Grafana : http://localhost:3000/
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    networks:
      bitdb-net:
        ipv4_address: 172.21.0.15
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel

volumes:
  grafana-storage:

networks:
  bitdb-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
