version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - bitdb
    volumes:
       - ./mongo:/data/db
  bitcored:
    image: dalijolijo/bitcored-bitdb
    container_name: bitcored-bitdb
    command: -rpcuser=root -rpcpassword=bitcore
    networks:
      - bitdb
    restart: always
    ports:
      - "8555:8555"
    volumes:
       - ./bitcore:/data 
  bitdb-btx:
    build:
      context: "./docker"
      dockerfile: "./Dockerfile.bitdb-btx"
    image: docker-bitd-btx
    container_name: bitdb-btx
    working_dir: "/bitdb"
    command: bash -c "sleep 60 && npm start"
    restart: always
    networks:
      - bitdb
    depends_on:
      - mongo
      - bitcored
  bitserve:
    build:
      context: "./docker"
      dockerfile: "./Dockerfile.bitserve"
    image: docker-bitserve
    container_name: bitserve
    working_dir: "/bitserve"
    command: bash -c "sleep 10 && npm start"
    restart: always
    networks:
      - bitdb
    depends_on:
      - mongo
    ports:
      - 3000:3000

networks:
  bitdb:
